MVC/Controllers/GenresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Business.Models;
using Business.Services;
using Business;
using System.ComponentModel.Design;
using Elfie.Serialization;

//Generated from Custom Template.
namespace MVC.Controllers
{
    public class GenresController : Controller
    {
        // TODO: Add service injections here
        private readonly IGenreService _genreService;
        private readonly IMovieService _movieService;
        public GenresController(IGenreService genreService,IMovieService movieService)
        {
            _genreService = genreService;
            _movieService = movieService;
        }

        // GET: Genres
        public IActionResult Index()
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Login", "Directors"); // Change "Home" to the appropriate controller
            }

            List<GenreModel> genreList = _genreService.GetList(); // TODO: Add get list service logic here
            return View(genreList);
        }

        // GET: Genres/Details/5
        public IActionResult Details(int id)
        {
            GenreModel genre = _genreService.GetItem(id); ; // TODO: Add get item service logic here
            if (genre == null)
            {
                return View("_Error", "Genre not found!"); ;
            }
            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {

            ViewBag.MovieId = new MultiSelectList(_movieService.Query().ToList(), "Id", "Name");
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GenreModel genre)
        {
            if (ModelState.IsValid)
            {
                var result = _genreService.Add(genre);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.MovieId = new MultiSelectList(_movieService.Query().ToList(), "Id", "Name");
            return View(genre);
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            
        }

        // GET: Genres/Edit/5
        public IActionResult Edit(int id)
        {
            GenreModel genre = _genreService.GetItem(id); // TODO: Add get item service logic here
            if (genre == null)
            {
                return View("_Error", "Genre not found!");
            }
            ViewBag.MovieId = new MultiSelectList(_movieService.Query().ToList(), "Id", "Name");
            
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(genre);
        }

        // POST: Genres/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GenreModel genre)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                var result = _genreService.Update(genre);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    // Way 1: 
                    //return RedirectToAction(nameof(Index));
                    // Way 2: redirection with route values
                    return RedirectToAction(nameof(Details), new { id = genre.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(genre);
        }

        // GET: Genres/Delete/5
        public IActionResult Delete(int id)
        {
            var result = _genreService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
        // POST: Genres/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            return RedirectToAction(nameof(Index));
        }
    }

       
	}

MVC/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Business;
using Business.Models;
using Business.Services;
using Business.Results.Bases;
using Microsoft.AspNetCore.Authorization;

//Generated from Custom Template.
namespace MVC.Controllers
{
    public class MoviesController : Controller
    {
        // TODO: Add service injections here
        private readonly IMovieService _movieService;
        private readonly IDirectoryService _directoryService;


		public MoviesController(IMovieService movieService,IDirectoryService directoryService)
        {
            _movieService = movieService;
            _directoryService = directoryService;
        }

        // GET: Movies
        public IActionResult Index(string searchString)
        {
            List<MovieModel> movieList = _movieService.Query().ToList();
            if (!string.IsNullOrEmpty(searchString))
            {
                movieList = movieList.Where(m => m.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            // TODO: Add get list service logic here
            return View(movieList);
        }

        // GET: Movies/Details/5
        public IActionResult Details(int id)
        {
            MovieModel movie = _movieService.Query().SingleOrDefault(u => u.Id == id); // TODO: Add get item service logic here
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        // TODO: Add service injections here
        // TODO: Add service injections here
        [Authorize]
        public IActionResult Create()
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Index", "Home"); // Change "Home" to the appropriate controller
            }

            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewBag.Directors = new SelectList(_directoryService.Query().ToList(), "Id", "UserName");
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MovieModel movie)
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Index", "Home"); // Change "Home" to the appropriate controller
            }

            if (ModelState.IsValid)
            {
                // If model data is valid, insert service logic should be written here.
                Result result = _movieService.Add(movie);

                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", result.Message);
            }

            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewBag.Directors = new SelectList(_directoryService.Query().ToList(), "Id", "UserName");
            return View(movie);
        }
        // GET: Movies/Edit/5
        public IActionResult Edit(int id)
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Login", "Directors"); // Change "Home" to the appropriate controller
            }

            MovieModel movie = _movieService.Query().SingleOrDefault(u => u.Id == id); ; // TODO: Add get item service logic here
            if (movie == null)
            {
                return NotFound();
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewBag.Directors = new SelectList(_directoryService.Query().ToList(), "Id", "UserName");
            return View(movie);
        }

        // POST: Movies/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MovieModel movie)
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Login", "Directors"); // Change "Home" to the appropriate controller
            }

            if (ModelState.IsValid)
            {
                var result = _movieService.Update(movie); // update the user in the service
                if (result.IsSuccessful)
                {
                    // if update operation result is successful, carry successful result message to the List view through the GetList action
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewBag.Directors = new SelectList(_directoryService.Query().ToList(), "Id", "UserName");
            return View(movie);
        }

        // GET: Movies/Delete/5
        public IActionResult Delete(int id)
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Login", "Directors"); // Change "Home" to the appropriate controller
            }

            MovieModel movie = _movieService.Query().SingleOrDefault(u => u.Id == id); // TODO: Add get item service logic here
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (!User.HasClaim("Director", "true"))
            {
                // If the user is not a director, redirect to the index page
                return RedirectToAction("Login", "Directors"); // Change "Home" to the appropriate controller
            }

            var result = _movieService.DeleteUser(id);
            TempData["Message"] = result.Message;
            // TODO: Add delete service logic here
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MovieHomework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
    <style>
        body {
            padding-top: 56px;
        }

        header {
            background-color: #007bff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .navbar-brand {
            color: #fff;
            font-weight: bold;
        }

        .navbar-toggler-icon {
            background-color: #fff;
        }

        .navbar-nav .nav-link {
            color: #000;
        }

        main {
            padding-top: 20px;
        }

        footer {
            padding: 20px 0;
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Directors" asp-action="Index">Directors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>
                         @{
            if (User.HasClaim("Director", "true"))
            {
                                <form asp-controller="Directors" asp-action="Logout" method="post" class="form-inline">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="btn btn-danger">Logout</button>
                                </form>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Directors" asp-action="Login">Login</a>
                                </li>
                            }
                        }
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - MovieProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>